#!/usr/bin/env bash

set -eu

function forEachMarkdown {
    for f in $(find ./src/ -type f | grep -e '.md$' | grep -v "SUMMARY.md"); do
        "$@" "$f"
    done
}

function sedFile {
    sed -i "s;$1;$2;g" "$3"
}

function encloseWordBy {
    WORD=$1;shift
    BY=$1;shift
    FILE=$1;shift
    sedFile "\\([^$BY]\\)\\($WORD\\)\\([^$BY]\\)" "\1$BY$WORD$BY\3" "$FILE"
}

function underlineWord {
    encloseWordBy "$1" "_" "$2"
}

forEachMarkdown underlineWord derivations
forEachMarkdown underlineWord derivation
forEachMarkdown underlineWord hashmap
forEachMarkdown underlineWord hashtable

